GET {{host}}
Content-Type: application/json

###

POST {{host}}/registration
Content-Type: application/json

{
  "username": "test1",
  "password":"12345678",
  "email": "test1@test.ru"
}

###

POST {{host}}/login
Content-Type: application/json

{
  "username": "test1",
  "password":"12345678"
}

###

POST {{host}}/movie/add
Content-Type: application/json
Authorization: {{token}}

{
  "Name": "Рога и копыта",
  "Rating_kp": 8.2,
  "Rating_imdb": 4.2,
  "Kinopoisk_id": 123124,
  "Rating_avg": 9.1,
  "Preview": "test preview",
  "Trailer": "testube.ru/test_url/",
  "Genre": "Comedy",
  "Year": 2001,
  "Type": "Cartoon"
}